#!/bin/bash

# Automatic installation and configuration of Arch Linux.
# Author: Bogachenko Vyacheslav
# Mail: bogachenkove@gmail.com

loadkeys ru
setfont cyr-sun16
timedatectl set-ntp true

echo "Вы хотите использовать cfdisk или fdisk для создания разделов диска?"
read -p "1 - cfdisk, 0 - fdisk: " mark_disk
if [[ $mark_disk == 0 ]]; then
	cfdisk
elif [[ $mark_disk == 1 ]]; then
	fdisk /dev/sda
fi
fdisk -l

parted

mount /dev/sda2 /mnt
mkdir /mnt/{boot,home}
mount /dev/sda1 /mnt/boot
swapon /dev/sda3
mount /dev/sda4 /mnt/home
pacstrap /mnt base base-devel linux linux-firmware vim dhcpcd netctl
genfstab -pU /mnt >> /mnt/etc/fstab
arch-chroot /mnt
echo "bogachenko" >> /etc/hostname
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
echo "ru_RU.UTF-8 UTF-8" >> /etc/locale.gen 
locale-gen
echo 'LANG="ru_RU.UTF-8"' > /etc/locale.conf
echo 'KEYMAP=ru' >> /etc/vconsole.conf
echo 'FONT=cyr-sun16' >> /etc/vconsole.conf
mkinitcpio -p linux
pacman -Syy
pacman -S grub --noconfirm 
grub-install /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg
pacman -S dialog wpa_supplicant --noconfirm
useradd -m -g users -G wheel -s /bin/bash bogachenko
passwd
passwd bogachenko
echo '%wheel ALL=(ALL) ALL' >> /etc/sudoers
echo '[multilib]' >> /etc/pacman.conf
echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
pacman -Syy
echo "Куда устанавливем Arch Linux на виртуальную машину?"
read -p "1 - Да, 0 - Нет: " vm_setting
if [[ $vm_setting == 0 ]]; then
  gui_install="xorg-server xorg-drivers xorg-xinit"
elif [[ $vm_setting == 1 ]]; then
  gui_install="xorg-server xorg-drivers xorg-xinit virtualbox-guest-utils"
fi
pacman -S $gui_install
echo "Какое DE ставим?"
read -p "1 - XFCE, 2 - KDE, 3 - Openbox, 4 - i3 WM: " vm_setting
if [[ $vm_setting == 1 ]]; then
  pacman -Sy xfce4 xfce4-goodies --noconfirm
elif [[ $vm_setting == 2 ]]; then
  pacman -Sy plasma-meta kdebase plasma-wayland-session --noconfirm
elif [[ $vm_setting == 3 ]]; then
  pacman -Sy  openbox xfce4-terminal
elif [[ $vm_setting == 4 ]]; then
  pacman -Sy i3 --noconfirm
fi
pacman -S lxdm --noconfirm
systemctl enable lxdm
pacman -S ttf-liberation ttf-dejavu --noconfirm
pacman -S networkmanager network-manager-applet ppp --noconfirm
systemctl enable NetworkManager
exit